version: "3.7"

volumes:
  postgres:

networks:
  lp_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/8

services:
  main:
    build:
      context: .
      dockerfile: ./cmd/main/Dockerfile
    env_file:
      - .env
    depends_on:
      - authorization
      - profile
      - music
    ports:
      - "3030:3030"
    networks:
      lp_network:
        ipv4_address: 10.5.0.2

  authorization:
    build:
      context: .
      dockerfile: ./cmd/authorization/Dockerfile
    env_file:
      - .env
    networks:
      lp_network:
        ipv4_address: 10.5.0.3

  profile:
    build:
      context: .
      dockerfile: ./cmd/profile/Dockerfile
    env_file:
      - .env
    networks:
      lp_network:
        ipv4_address: 10.5.0.4

  music:
    build:
      context: .
      dockerfile: ./cmd/music/Dockerfile
    env_file:
      - .env
    networks:
      lp_network:
        ipv4_address: 10.5.0.5
