version: "3.7"

volumes:
  postgres:

services:
  main:
    build:
      context: .
      dockerfile: ./cmd/main/Dockerfile
    env_file:
      - .env
    depends_on:
      - authorization
      - profile
      - music
    ports:
      - "3030:3030"

  authorization:
    build:
      context: .
      dockerfile: ./cmd/authorization/Dockerfile
    env_file:
      - .env
    ports:
      - "3080:3080"

  profile:
    build:
      context: .
      dockerfile: ./cmd/profile/Dockerfile
    env_file:
      - .env
    ports:
      - "3081:3081"

  music:
    build:
      context: .
      dockerfile: ./cmd/music/Dockerfile
    env_file:
      - .env
    ports:
      - "3082:3082"
