global:
  scrape_interval: 5m
  scrape_timeout: 1m
  evaluation_interval: 10s

scrape_configs:
  - job_name: "server"
    scrape_interval: 5s
    static_configs:
      - targets: [ '10.5.0.2:3030' ]
        labels:
          group: 'main_server'

  - job_name: "system_status"
    scrape_interval: 5s
    static_configs:
      - targets: [ '10.5.0.10:9100' ]


rule_files:
  - "alert.rules"
