global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "server"
    scrape_interval: 5s
    static_configs:
      - targets: [ "localhost:3030" ]
        labels:
          group: 'main_server'

  - job_name: "system_status"
    scrape_interval: 5s
    static_configs:
      - targets: [ 'localhost:3030' ]


rule_files:
  - "alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ "alertmanager:9092" ]
