// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"2021_2_LostPointer/internal/album"
	"2021_2_LostPointer/internal/models"
	"sync"
)

// Ensure, that MockAlbumRepository does implement album.AlbumRepository.
// If this is not the case, regenerate this file with moq.
var _ album.AlbumRepository = &MockAlbumRepository{}

// MockAlbumRepository is a mock implementation of album.AlbumRepository.
//
// 	func TestSomethingThatUsesAlbumRepository(t *testing.T) {
//
// 		// make and configure a mocked album.AlbumRepository
// 		mockedAlbumRepository := &MockAlbumRepository{
// 			GetByArtistIDFunc: func(id int, amount int) ([]models.Album, error) {
// 				panic("mock out the GetByArtistID method")
// 			},
// 			GetRandomFunc: func(amount int) ([]models.Album, error) {
// 				panic("mock out the GetRandom method")
// 			},
// 		}
//
// 		// use mockedAlbumRepository in code that requires album.AlbumRepository
// 		// and then make assertions.
//
// 	}
type MockAlbumRepository struct {
	// GetByArtistIDFunc mocks the GetByArtistID method.
	GetByArtistIDFunc func(id int, amount int) ([]models.Album, error)

	// GetRandomFunc mocks the GetRandom method.
	GetRandomFunc func(amount int) ([]models.Album, error)

	// calls tracks calls to the methods.
	calls struct {
		// GetByArtistID holds details about calls to the GetByArtistID method.
		GetByArtistID []struct {
			// ID is the id argument value.
			ID int
			// Amount is the amount argument value.
			Amount int
		}
		// GetRandom holds details about calls to the GetRandom method.
		GetRandom []struct {
			// Amount is the amount argument value.
			Amount int
		}
	}
	lockGetByArtistID sync.RWMutex
	lockGetRandom     sync.RWMutex
}

// GetByArtistID calls GetByArtistIDFunc.
func (mock *MockAlbumRepository) GetByArtistID(id int, amount int) ([]models.Album, error) {
	if mock.GetByArtistIDFunc == nil {
		panic("MockAlbumRepository.GetByArtistIDFunc: method is nil but AlbumRepository.GetByArtistID was just called")
	}
	callInfo := struct {
		ID     int
		Amount int
	}{
		ID:     id,
		Amount: amount,
	}
	mock.lockGetByArtistID.Lock()
	mock.calls.GetByArtistID = append(mock.calls.GetByArtistID, callInfo)
	mock.lockGetByArtistID.Unlock()
	return mock.GetByArtistIDFunc(id, amount)
}

// GetByArtistIDCalls gets all the calls that were made to GetByArtistID.
// Check the length with:
//     len(mockedAlbumRepository.GetByArtistIDCalls())
func (mock *MockAlbumRepository) GetByArtistIDCalls() []struct {
	ID     int
	Amount int
} {
	var calls []struct {
		ID     int
		Amount int
	}
	mock.lockGetByArtistID.RLock()
	calls = mock.calls.GetByArtistID
	mock.lockGetByArtistID.RUnlock()
	return calls
}

// GetRandom calls GetRandomFunc.
func (mock *MockAlbumRepository) GetRandom(amount int) ([]models.Album, error) {
	if mock.GetRandomFunc == nil {
		panic("MockAlbumRepository.GetRandomFunc: method is nil but AlbumRepository.GetRandom was just called")
	}
	callInfo := struct {
		Amount int
	}{
		Amount: amount,
	}
	mock.lockGetRandom.Lock()
	mock.calls.GetRandom = append(mock.calls.GetRandom, callInfo)
	mock.lockGetRandom.Unlock()
	return mock.GetRandomFunc(amount)
}

// GetRandomCalls gets all the calls that were made to GetRandom.
// Check the length with:
//     len(mockedAlbumRepository.GetRandomCalls())
func (mock *MockAlbumRepository) GetRandomCalls() []struct {
	Amount int
} {
	var calls []struct {
		Amount int
	}
	mock.lockGetRandom.RLock()
	calls = mock.calls.GetRandom
	mock.lockGetRandom.RUnlock()
	return calls
}
