// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mock

import (
	"2021_2_LostPointer/internal/models"
	"2021_2_LostPointer/internal/track"
	"sync"
)

// Ensure, that MockTrackRepository does implement track.TrackRepository.
// If this is not the case, regenerate this file with moq.
var _ track.TrackRepository = &MockTrackRepository{}

// MockTrackRepository is a mock implementation of track.TrackRepository.
//
// 	func TestSomethingThatUsesTrackRepository(t *testing.T) {
//
// 		// make and configure a mocked track.TrackRepository
// 		mockedTrackRepository := &MockTrackRepository{
// 			GetByAlbumIDFunc: func(albumID int, isAuthorized bool) ([]models.Track, error) {
// 				panic("mock out the GetByAlbumID method")
// 			},
// 			GetByArtistIDFunc: func(artistID int, amount int, isAuthorized bool) ([]models.Track, error) {
// 				panic("mock out the GetByArtistID method")
// 			},
// 			GetRandomFunc: func(amount int, isAuthorized bool) ([]models.Track, error) {
// 				panic("mock out the GetRandom method")
// 			},
// 			IncrementListenCountFunc: func(n int64) error {
// 				panic("mock out the IncrementListenCount method")
// 			},
// 		}
//
// 		// use mockedTrackRepository in code that requires track.TrackRepository
// 		// and then make assertions.
//
// 	}
type MockTrackRepository struct {
	// GetByAlbumIDFunc mocks the GetByAlbumID method.
	GetByAlbumIDFunc func(albumID int, isAuthorized bool) ([]models.Track, error)

	// GetByArtistIDFunc mocks the GetByArtistID method.
	GetByArtistIDFunc func(artistID int, amount int, isAuthorized bool) ([]models.Track, error)

	// GetRandomFunc mocks the GetRandom method.
	GetRandomFunc func(amount int, isAuthorized bool) ([]models.Track, error)

	// IncrementListenCountFunc mocks the IncrementListenCount method.
	IncrementListenCountFunc func(n int64) error

	// calls tracks calls to the methods.
	calls struct {
		// GetByAlbumID holds details about calls to the GetByAlbumID method.
		GetByAlbumID []struct {
			// AlbumID is the albumID argument value.
			AlbumID int
			// IsAuthorized is the isAuthorized argument value.
			IsAuthorized bool
		}
		// GetByArtistID holds details about calls to the GetByArtistID method.
		GetByArtistID []struct {
			// ArtistID is the artistID argument value.
			ArtistID int
			// Amount is the amount argument value.
			Amount int
			// IsAuthorized is the isAuthorized argument value.
			IsAuthorized bool
		}
		// GetRandom holds details about calls to the GetRandom method.
		GetRandom []struct {
			// Amount is the amount argument value.
			Amount int
			// IsAuthorized is the isAuthorized argument value.
			IsAuthorized bool
		}
		// IncrementListenCount holds details about calls to the IncrementListenCount method.
		IncrementListenCount []struct {
			// N is the n argument value.
			N int64
		}
	}
	lockGetByAlbumID         sync.RWMutex
	lockGetByArtistID        sync.RWMutex
	lockGetRandom            sync.RWMutex
	lockIncrementListenCount sync.RWMutex
}

// GetByAlbumID calls GetByAlbumIDFunc.
func (mock *MockTrackRepository) GetByAlbumID(albumID int, isAuthorized bool) ([]models.Track, error) {
	if mock.GetByAlbumIDFunc == nil {
		panic("MockTrackRepository.GetByAlbumIDFunc: method is nil but TrackRepository.GetByAlbumID was just called")
	}
	callInfo := struct {
		AlbumID      int
		IsAuthorized bool
	}{
		AlbumID:      albumID,
		IsAuthorized: isAuthorized,
	}
	mock.lockGetByAlbumID.Lock()
	mock.calls.GetByAlbumID = append(mock.calls.GetByAlbumID, callInfo)
	mock.lockGetByAlbumID.Unlock()
	return mock.GetByAlbumIDFunc(albumID, isAuthorized)
}

// GetByAlbumIDCalls gets all the calls that were made to GetByAlbumID.
// Check the length with:
//     len(mockedTrackRepository.GetByAlbumIDCalls())
func (mock *MockTrackRepository) GetByAlbumIDCalls() []struct {
	AlbumID      int
	IsAuthorized bool
} {
	var calls []struct {
		AlbumID      int
		IsAuthorized bool
	}
	mock.lockGetByAlbumID.RLock()
	calls = mock.calls.GetByAlbumID
	mock.lockGetByAlbumID.RUnlock()
	return calls
}

// GetByArtistID calls GetByArtistIDFunc.
func (mock *MockTrackRepository) GetByArtistID(artistID int, amount int, isAuthorized bool) ([]models.Track, error) {
	if mock.GetByArtistIDFunc == nil {
		panic("MockTrackRepository.GetByArtistIDFunc: method is nil but TrackRepository.GetByArtistID was just called")
	}
	callInfo := struct {
		ArtistID     int
		Amount       int
		IsAuthorized bool
	}{
		ArtistID:     artistID,
		Amount:       amount,
		IsAuthorized: isAuthorized,
	}
	mock.lockGetByArtistID.Lock()
	mock.calls.GetByArtistID = append(mock.calls.GetByArtistID, callInfo)
	mock.lockGetByArtistID.Unlock()
	return mock.GetByArtistIDFunc(artistID, amount, isAuthorized)
}

// GetByArtistIDCalls gets all the calls that were made to GetByArtistID.
// Check the length with:
//     len(mockedTrackRepository.GetByArtistIDCalls())
func (mock *MockTrackRepository) GetByArtistIDCalls() []struct {
	ArtistID     int
	Amount       int
	IsAuthorized bool
} {
	var calls []struct {
		ArtistID     int
		Amount       int
		IsAuthorized bool
	}
	mock.lockGetByArtistID.RLock()
	calls = mock.calls.GetByArtistID
	mock.lockGetByArtistID.RUnlock()
	return calls
}

// GetRandom calls GetRandomFunc.
func (mock *MockTrackRepository) GetRandom(amount int, isAuthorized bool) ([]models.Track, error) {
	if mock.GetRandomFunc == nil {
		panic("MockTrackRepository.GetRandomFunc: method is nil but TrackRepository.GetRandom was just called")
	}
	callInfo := struct {
		Amount       int
		IsAuthorized bool
	}{
		Amount:       amount,
		IsAuthorized: isAuthorized,
	}
	mock.lockGetRandom.Lock()
	mock.calls.GetRandom = append(mock.calls.GetRandom, callInfo)
	mock.lockGetRandom.Unlock()
	return mock.GetRandomFunc(amount, isAuthorized)
}

// GetRandomCalls gets all the calls that were made to GetRandom.
// Check the length with:
//     len(mockedTrackRepository.GetRandomCalls())
func (mock *MockTrackRepository) GetRandomCalls() []struct {
	Amount       int
	IsAuthorized bool
} {
	var calls []struct {
		Amount       int
		IsAuthorized bool
	}
	mock.lockGetRandom.RLock()
	calls = mock.calls.GetRandom
	mock.lockGetRandom.RUnlock()
	return calls
}

// IncrementListenCount calls IncrementListenCountFunc.
func (mock *MockTrackRepository) IncrementListenCount(n int64) error {
	if mock.IncrementListenCountFunc == nil {
		panic("MockTrackRepository.IncrementListenCountFunc: method is nil but TrackRepository.IncrementListenCount was just called")
	}
	callInfo := struct {
		N int64
	}{
		N: n,
	}
	mock.lockIncrementListenCount.Lock()
	mock.calls.IncrementListenCount = append(mock.calls.IncrementListenCount, callInfo)
	mock.lockIncrementListenCount.Unlock()
	return mock.IncrementListenCountFunc(n)
}

// IncrementListenCountCalls gets all the calls that were made to IncrementListenCount.
// Check the length with:
//     len(mockedTrackRepository.IncrementListenCountCalls())
func (mock *MockTrackRepository) IncrementListenCountCalls() []struct {
	N int64
} {
	var calls []struct {
		N int64
	}
	mock.lockIncrementListenCount.RLock()
	calls = mock.calls.IncrementListenCount
	mock.lockIncrementListenCount.RUnlock()
	return calls
}
