name: deploy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
      - main

jobs:
  tests:
    name: Run tests
    runs-on: self-hosted
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run all tests
        run: make tests

  linter:
    needs: tests
    name: Run linter
    runs-on: self-hosted
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
          make lint

  build:
    needs: linter
    name: Build Docker
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: los-98
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push authorization
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/authorization/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vershovbmstu/lostpointer_deploy_authorization:latest
      - name: Build and push music
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/music/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vershovbmstu/lostpointer_deploy_music:latest
      - name: Build and push playlists
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/playlists/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vershovbmstu/lostpointer_deploy_playlists:latest
      - name: Build and push profile
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/profile/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vershovbmstu/lostpointer_deploy_profile:latest
      - name: Build and push main
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./cmd/main/Dockerfile
          platforms: linux/arm64
          push: true
          tags: vershovbmstu/lostpointer_deploy_main:latest
 
  deploy:
    needs: build
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: los-98
      - name: copy file via rsync
        run : |
          rsync -a ./docker-compose-cd.yml ${{ secrets.TARGET_PATH }}
      - name: Pull docker images
        run : |
            cd ${{ secrets.TARGET_PATH }} && sudo docker-compose -f docker-compose-cd.yml pull
      - name: Run docker-compose
        run : |
            cd ${{ secrets.TARGET_PATH }} && sudo docker-compose -f docker-compose-cd.yml up --build -d
