name: deploy

on:
  push:
    branches:
      - dev
      - los-98
  pull_request:
    branches:
      - dev
      - main

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run all tests
        run: make tests