name: deploy

on:
  push:
    branches:
      - dev
      - los-98
  pull_request:
    branches:
      - dev
      - main

jobs:
#  tests:
#    name: Run tests
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.16.x'
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Run all tests
#        run: make tests
#  linter:
#    name: Run linter
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: '1.16.x'
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Run linter
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          go get github.com/golangci/golangci-lint/cmd/golangci-lint
#          make lint
  build:
    name: Build Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: los-98
      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: "vershovbmstu"
          password: "Avt8430055"
      - name: Push to Docker Hub
        env:
          DBUSER: postgres
          DBPASS: root
          DBNAME: lostpointer
          PG_EXTERNAL_PORT: 54321
          REDIS_EXTERNAL_PORT: 63799
        run: |
          docker-compose build -f docker-compose.yml
          docker tag 2021_2_lostpointer_main vershovbmstu/lostpointer_deploy_main:latest
          docker push vershovbmstu/lostpointer_deploy_main:latest
          docker tag 2021_2_lostpointer_authorization vershovbmstu/lostpointer_deploy_authorization:latest
          docker push vershovbmstu/lostpointer_deploy_authorization:latest
          docker tag 2021_2_lostpointer_music vershovbmstu/lostpointer_deploy_music:latest
          docker push vershovbmstu/lostpointer_deploy_music:latest
          docker tag 2021_2_lostpointer_profile vershovbmstu/lostpointer_deploy_profile:latest
          docker push vershovbmstu/lostpointer_deploy_profile:latest
          docker tag 2021_2_lostpointer_playlists vershovbmstu/lostpointer_deploy_playlists:latest
          docker push vershovbmstu/lostpointer_deploy_playlists:latest



